spring:
  application.name: core-api
  config:
    import:
      - logging.yml
      - db.yml
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

hbc:
  plc:
    url: s7://hbc-plc.ohtgo.me
    publisher:
      enabled: true
  origins: http://localhost:5173

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
