apiPrefix: /api

spring:
  application.name: core-api
  config:
    import:
      - logging.yml
      - db.yml
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch.matching-strategy: ant_path_matcher
  web.resources.add-mappings: false
  mail:
    host: ${hbc.mail.host}
    port: ${hbc.mail.port}
    username: ${hbc.mail.username}
    password: ${hbc.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

hbc:
  plc:
    url: ${PLC_ADDRESS:s7://hbc-plc.ohtgo.me}
  origins: ${CORS_ORIGINS:http://localhost:5173}
  mail:
    host: ${MAIL_HOST:mail.smtp2go.com}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:rms@ohtgo.me}
    password: ${MAIL_PASSWORD:P@ssw0rd000}
    from: ${MAIL_FROM:RMS <rms@ohtgo.me>}
    subject: ${MAIL_SUBJECT:Alarm notification}
  push:
    url: ${PUSH_URL:https://ntfy.ohtgo.me}
    auth: ${PUSH_AUTH:YWRtaW46UEBzc3cwcmQwMDA=}
    title: ${PUSH_TITLE:RMS}
  security:
    jwt:
      secret-key: ${JWT_SECRET:ZGNtLXRoYW5nLW5hby1kZWNvZGUtY2FpLW5heS1uaGFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ==}
      expiration-time: ${JWT_EXPIRATION_TIME:86400000}
  report:
    enable-validation: ${REPORT_VALIDATE:true}
    dir: ${REPORT_DIR:D:/reports}
server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
