spring:
  liquibase:
    enabled: false
    changelog: classpath:/master-changelog.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        format_sql: false
        show_sql: false

integration:
  datasource:
    core:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=F-PMS}
      username: ${DATABASE_USER:sa}
      password: ${DATABASE_PASSWORD:dev@123}
      pool-name: db-pool
      data-source-properties:
        rewriteBatchedStatements: true