spring:
  liquibase:
    enabled: true
hbc:
  plc:
    url: mock:scraper
  report:
    enable-validation: false
integration:
  datasource:
    core:
      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
      jdbc-url: jdbc:tc:sqlserver:2017-CU12:///F-PMS
      pool-name: db-pool
      data-source-properties:
        rewriteBatchedStatements: true