name: CI

on:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  general-ci:
    uses: f-pms/Devops/.github/workflows/ci.yaml@huynn/linter
  java-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git merge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      - name: Execute Gradle build
        run: ./gradlew build