name: CI
on:
  pull_request:
    branches:
      - master

permissions:
    contents: read
    pull-requests: read

jobs:
  ci:
    uses: f-pms/Devops/.github/workflows/ci.yaml@master
    with:
        prepare-command: |
          echo "A initial message"
          pip install -r requirements.txt
          echo "Another message or command"
          python myscript.py
          bash some-shell-script-file.sh -xe
        build-command: echo "Building...!"
        test-command: echo "Testing...!"
  java-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629