# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version to deploy'
        default: '0.0.1'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
